// src/template-vue3-ts-pinia-router-element-unocss/src/layout/Header/index.vue
<script setup lang="ts">
import { navList } from './config';
const skip = (url: string) => {
  window.open(url, '_self');
};
</script>

<template>
  <div class="header-container">
    <div class="header-logo">
      <a href="https://vitejs.dev" target="_blank">
        <img src="/vite.svg" class="logo" alt="Vite logo" />
      </a>
    </div>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <!-- <span class="navbar-toggler-icon"></span> -->
          <svg-icon :name="'open'"></svg-icon>
        </button>
        <div
          class="nav-list collapse navbar-collapse"
          id="navbarSupportedContent"
        >
          <ul class="mb-2 navbar-nav me-auto mb-lg-0">
            <li
              class="nav-item"
              v-for="item in navList.data"
              :key="item.id"
              @click="skip(item.url)"
            >
              <a class="nav-link active" aria-current="page" href="#">{{
                item.name
              }}</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</template>

<style scoped lang="scss">
.header-container {
  // position: relative;
  // width: 100vw;
  max-width: 1200px;
  display: flex;
  justify-content: space-between;
  vertical-align: middle;
  .header-logo {
    padding-right: 30px;
    // 居中
    display: flex;
    justify-content: center;
    align-items: center;
    .logo {
      width: 40px;
      height: 40px;
    }
  }
  @media screen and (max-width: 991px) {
    .header-logo {
      position: absolute;
      // 居中
      left: 50%;
      transform: translateX(-50%);
    }
  }
  .navbar {
    width: 100%;
    .nav-list {
      ul li {
        a {
          @include themeChildify {
            color: themed("font-color");
          }
          &:hover {
            @include themeChildify {
              color: themed("font-color-second");
            }
          }
        }
      }
    }
  }
}
@media screen and (min-width: 1200px) {
  .header-container {
    width: 1200px;
    margin: 0 auto;
  }
}
</style>

// src/template-react-ts-redux-router/src/layouts/Header/index.tsx
import React, { useRef } from 'react'
import { navList } from './navList'
import { Navbar, Container, Nav } from 'react-bootstrap'
import SvgIcon from '@/components/SvgIcon'
import { useNavigate } from 'react-router-dom'
import './index.scss'
import { useScroll } from 'ahooks';
export default function Header() {
    const navigate = useNavigate()
    const ref = useRef(null);
    const scroll = useScroll(ref);
    return (
        <div className="h-full w-1200px">
            <Navbar collapseOnSelect expand="md" className='header-container m-0 p-0'>
                <Container fluid className="header-container h-full flex justify-between">
                    <Navbar.Brand href="#" className="header-left h-14 flex items-center pl-10">
                        <div className="header-logo-container w-30 h-16 flex items-center">
                            <div className='h-14'>
                                <SvgIcon name="react" iconStyle={{ color: "linear-gradient(to right, rgba(0,0,0), rgba(255,255,255))", width: "50px", height: "50px" }} />
                            </div>
                        </div>
                    </Navbar.Brand>
                    <Navbar.Toggle aria-controls="navbarScroll" />
                    <Navbar.Collapse id="navbarScroll" className="header-nav-container me-auto">
                        <Nav className="me-auto">
                            {
                                navList.map((item, index) => {
                                    return (
                                        <Nav.Link key={index} onClick={() => { navigate(item.path) }} className='header-nav-item font-bold font-mono text-lg px-3 cursor-pointer'>{item.name}</Nav.Link>
                                    )
                                })
                            }
                        </Nav>
                    </Navbar.Collapse>
                    <Navbar.Collapse id="navbarScroll" className="header-nav-container me-auto text-right">
                        <Nav className='w-full'>
                            <Nav.Link className='header-nav-item font-bold font-mono text-lg px-3 w-full cursor-pointer'>登录</Nav.Link>
                        </Nav>
                    </Navbar.Collapse>
                </Container>
            </Navbar>
        </div>
    )
}
